language: node_js
sudo: false
node_js:
  - "8"
  - "10"
install:
  - npm install
stages:
  - lint
  - build  
jobs:
  include:
    - stage: lint
      script:
        - npm run lint                
    - stage: build
      script:
        - npm run build
deploy:
  provider: npm
  email: "mehmetbaran@mehmetbaran.net"
  api_key: "$NPM_TOKEN"
  on:
    branch: master