language: node_js
node_js:
 - 10
install:
  - npm install
stages:
  - lint
  - deploy  
jobs:
  include:
    - stage: lint
      script:
        - npm run lint                
    - stage: deploy
      script: npm run build     # usually you do not want to rerun any tests
      deploy:
        provider: npm
        email: "mehmetbaran@mehmetbaran.net"
        api_key: "$NPM_TOKEN"
        before_deploy: "npm run build"
        on:
          branch: master
