language: node_js
sudo: false
node_js:
 - 10
install:
  - npm install
script:
  - npm run lint
  - npm run build
  - ls
  - ls dist
deploy:
  provider: npm
  email: "mehmetbaran@mehmetbaran.net"
  api_key: "$NPM_TOKEN"
  on:
    branch: master
